### PR TITLE
Add GermanTech Jobs - dedicated tech job board for Germany

### PR DESCRIPTION
**Pull request by MariaAbadi**

### CODE REVIEW

**Comment by MariaAbadi** [comment]
@tradziej would you mind having a look? :)

**Comment by tradziej** [comment]
Yes, sorry for the delay. Can you add your page to the list in alphabetical order? Thanks!

**Comment by MariaAbadi** [comment]
Sure, changed :)

**Comment by tradziej** [comment]
Thanks! Could you also squash your commits into one, please?

**Comment by MariaAbadi** [comment]
Should work now 😄

**Pull request merged**
